const DEFAULT_DESCRIPTIONS: Record<string, string> = {
  web_fetch: 'Fetch URL content as text. Args: { "url": string }',
  web_search: 'Search the web. Args: { "query": string }',
  execute_code: 'Run code in sandbox. Args: { "code": string, "language"?: string }',
  glob_files: 'Glob files under workspace. Args: { "pattern": string, "maxResults"?: number }',
  grep_search: 'Search file contents under workspace. Args: { "pattern": string, "path"?: string, "maxResults"?: number }',
  execute_code_pipeline: 'Run multi-step code in sandbox. Args: { "steps": [{ "code": string, "language"?: string }] }',
  file_read: 'Read file under workspace. Args: { "path": string }',
  file_write: 'Write file under workspace. Args: { "path": string, "content": string }',
  browser: 'Browser automation. Args: { "url": string, "action"?: "navigate"|"screenshot"|"content", "selector"?: string }',
  image_generate: 'Generate image via DALL-E. Args: { "prompt": string, "size"?: "1024x1024" }',
  text_to_speech: 'Synthesize speech (OpenAI TTS). Args: { "text": string }',
  memory_recall: 'Recall long-term memory entries. Args: { "query": string, "userId"?: string, "limit"?: number }',
  list_dir: 'List directory entries under workspace. Args: { "path"?: string }',
  edit_file: 'Replace text in a workspace file. Args: { "path": string, "old_string": string, "new_string": string, "replace_all"?: boolean }',
  run_shell: 'Run shell command via sandbox executor. Args: { "command": string }',
  http_request: 'HTTP request with method/headers/body. Args: { "url": string, "method"?: string, "headers"?: object, "body"?: string }',
  path_exists: 'Check if path exists in workspace. Args: { "path": string }',
  file_delete: 'Delete a file under workspace. Args: { "path": string }',
  append_file: 'Append text to a workspace file. Args: { "path": string, "content": string }',
  json_parse: 'Parse JSON text. Args: { "text": string }',
  datetime_now: 'Current datetime (ISO + unix). Args: { "timezone"?: string }',
  web_extract: 'Extract URL content as markdown. Args: { "url": string }',
  patch_file: 'Fuzzy patch file in workspace. Args: { "path", "old_string", "new_string" }',
  search_files: 'Search files by content or name. Args: { "pattern", "target"?: "content"|"name", "path"?, "maxResults"? }',
  browser_navigate: 'Navigate browser session. Args: { "url": string }',
  browser_snapshot: 'Page snapshot with element refs. Args: {}',
  browser_click: 'Click element by ref (@e1). Args: { "ref": string }',
  browser_type: 'Type into element by ref. Args: { "ref", "text" }',
  browser_scroll: 'Scroll page. Args: { "direction": "up"|"down", "amount"?: number }',
  browser_back: 'Browser back navigation. Args: {}',
  browser_press: 'Press keyboard key. Args: { "key": string }',
  browser_console: 'Get browser console logs. Args: {}',
  terminal: 'Run shell command (Hermes terminal). Args: { "command", "background"?: boolean }',
  process: 'Manage background processes. Args: { "action": "list"|"poll"|"log"|"kill", "processId"?: string }',
  todo: 'In-session task list. Args: { "todos"?: [...], "merge"?: boolean }',
  clarify: 'Ask user clarifying question. Args: { "question", "choices"?, "mode"? }',
  session_search: 'Search past sessions. Args: { "query", "limit"? }',
  vision_analyze: 'Analyze image URL or path. Args: { "image_url"|"path", "prompt"? }',
  kanban_list: 'List kanban tasks. Args: { "board"?, "column"? }',
  kanban_show: 'Show kanban task. Args: { "task_id" }',
  kanban_create: 'Create kanban task. Args: { "title", "description"?, "column"?, "board"? }',
  kanban_move: 'Move kanban task column. Args: { "task_id", "column" }',
  kanban_complete: 'Mark kanban task done. Args: { "task_id" }',
  kanban_block: 'Block agent on task. Args: { "task_id", "agent_id"?, "reason"? }',
  kanban_unblock: 'Unblock agent on task. Args: { "task_id", "agent_id"? }',
  kanban_heartbeat: 'Agent heartbeat on task. Args: { "task_id", "agent_id"?, "note"? }',
  kanban_comment: 'Add comment to task. Args: { "task_id", "comment" }',
  kanban_link: 'Link task to goal or task. Args: { "task_id", "link", "link_type"?: "goal"|"task" }',
  browser_get_images: 'List images on page. Args: {}',
  browser_vision: 'Vision-analyze current page screenshot. Args: { "prompt"? }',
  browser_dialog: 'Arm dialog handler. Args: { "action": "accept"|"dismiss", "text"? }',
  browser_cdp: 'Safe browser introspection. Set ANVIO_BROWSER_CDP_GRANT=1 for goto/click/fill. Args: { "method", "params"? }',
  delegate_task: 'Delegate to sub-agent. Args: { "agent", "task", "context"? }',
  cronjob: 'Manage cron automations. Args: { "action": "list"|"run"|"create", "slug"?, "schedule"?, "agent"?, "prompt"? }',
  skills_list: 'List workspace skills. Args: {}',
  skill_view: 'View skill instructions. Args: { "slug" }',
  send_message: 'Send user-visible message on channel. Args: { "message", "channel"? }',
  ha_list_entities: 'List Home Assistant entities. Args: { "domain"? } — env HOME_ASSISTANT_URL + TOKEN',
  ha_get_state: 'Get HA entity state. Args: { "entity_id" }',
  ha_list_services: 'List HA services. Args: {}',
  ha_call_service: 'Call HA service. Args: { "domain", "service", "entity_id"?, "data"? }',
  mixture_of_agents: 'Multi-agent synthesis. Args: { "task", "agents": string[], "synthesizer"? }',
  x_search: 'Search X/Twitter. Args: { "query", "limit"? }',
  video_analyze: 'Analyze video (ffmpeg frame extraction + vision) or image frame. Args: { "video_url"|"path", "prompt"? }',
  video_generate: 'Generate video (MCP video-gen server or mock). Args: { "prompt" }',
  computer_use: 'Desktop automation (macOS CUA). Args: { "action", "target"? }',
  discord_admin: 'Discord guild admin. Args: { "action": "list_channels"|"list_members", "guild_id" }',
  skill_manage: 'Manage skill drafts. Args: { "action": "promote"|"list_drafts", "slug"? }',
  spotify_search: 'Search Spotify (MCP or API). Args: { "query" }',
  feishu_doc_read: 'Read Feishu doc (MCP). Args: { "document_id" }',
  rl_tool: 'RL training ops via MCP, direct Tinker-Atropos HTTP, or mock. Args: { "action", "params"? }',
  yb_tool: 'Yuanbao group/DM/sticker ops via MCP or mock. Args: { "action", "params"? }',
};

export function describeBuiltinTool(toolName: string): string {
  const key = toolName.replace(/^anvio_tools__/, '');
  return DEFAULT_DESCRIPTIONS[key] ?? `Builtin tool ${toolName}`;
}

export function renderToolInstructions(toolNames: string[]): string {
  if (toolNames.length === 0) return '';

  const lines = toolNames.map((name) => `- ${name}: ${describeBuiltinTool(name)}`);
  return [
    '## Available tools',
    'When you need a tool, emit a fenced block exactly like:',
    '```anvio_tool',
    '{"name": "anvio_tools__web_fetch", "arguments": {"url": "https://example.com"}}',
    '```',
    'Wait for the tool result before continuing. Do not invent tool output.',
    '',
    ...lines,
  ].join('\n');
}
