#!/usr/bin/env bash
# Anvio installer — local-first AI Agent OS
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/viantonugroho11/Anvio/main/scripts/install.sh | bash
#   ./scripts/install.sh
#   ./scripts/install.sh --workspace ~/my-anvio

set -euo pipefail

ANVIO_REPO="${ANVIO_REPO:-https://github.com/viantonugroho11/Anvio.git}"
ANVIO_HOME="${ANVIO_HOME:-$HOME/.anvio}"
ANVIO_BIN_DIR="${ANVIO_BIN_DIR:-$HOME/.local/bin}"
ANVIO_WORKSPACE_DIR="${ANVIO_WORKSPACE:-$ANVIO_HOME/workspace}"
ANVIO_BRANCH="${ANVIO_BRANCH:-main}"
SKIP_BUILD=0

log() { printf '\033[1;34m[anvio]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[anvio]\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m[anvio]\033[0m %s\n' "$*" >&2; }

usage() {
  cat <<EOF
Anvio installer

Usage:
  install.sh [options]

Options:
  --workspace PATH   Workspace directory (default: ~/.anvio/workspace)
  --home PATH        Install root (default: ~/.anvio)
  --bin-dir PATH     Binary symlink dir (default: ~/.local/bin)
  --repo URL         Git repo URL (default: GitHub Anvio)
  --branch NAME      Git branch (default: main)
  --skip-build       Skip pnpm build (if already built)
  -h, --help         Show help

Environment:
  ANVIO_HOME, ANVIO_WORKSPACE, ANTHROPIC_API_KEY

After install:
  anvio chat
  anvio agents list
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace) ANVIO_WORKSPACE_DIR="$2"; shift 2 ;;
    --home) ANVIO_HOME="$2"; ANVIO_WORKSPACE_DIR="${ANVIO_WORKSPACE:-$ANVIO_HOME/workspace}"; shift 2 ;;
    --bin-dir) ANVIO_BIN_DIR="$2"; shift 2 ;;
    --repo) ANVIO_REPO="$2"; shift 2 ;;
    --branch) ANVIO_BRANCH="$2"; shift 2 ;;
    --skip-build) SKIP_BUILD=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) err "Unknown option: $1"; usage; exit 1 ;;
  esac
done

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "Required command not found: $1"
    exit 1
  fi
}

check_node() {
  need_cmd node
  local major
  major="$(node -p "process.versions.node.split('.')[0]")"
  if [[ "$major" -lt 20 ]]; then
    err "Node.js 20+ required (found: $(node -v))"
    err "Install from https://nodejs.org/ or use nvm/fnm"
    exit 1
  fi
  log "Node $(node -v) OK"
}

ensure_pnpm() {
  if command -v pnpm >/dev/null 2>&1; then
    log "pnpm $(pnpm -v) OK"
    return
  fi
  log "Enabling pnpm via corepack..."
  need_cmd corepack
  corepack enable
  corepack prepare pnpm@9.15.9 --activate
  log "pnpm $(pnpm -v) ready"
}

detect_install_dir() {
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  local candidate
  candidate="$(cd "$script_dir/.." && pwd)"

  if [[ -f "$candidate/package.json" ]] && grep -q '"name": "anvio"' "$candidate/package.json" 2>/dev/null; then
    echo "$candidate"
    return
  fi

  echo "$ANVIO_HOME/app"
}

install_source() {
  local install_dir="$1"

  if [[ -d "$install_dir/.git" ]] || [[ -f "$install_dir/package.json" ]]; then
    log "Using existing source at $install_dir"
    return
  fi

  log "Cloning Anvio to $install_dir ..."
  mkdir -p "$(dirname "$install_dir")"
  need_cmd git
  git clone --depth 1 --branch "$ANVIO_BRANCH" "$ANVIO_REPO" "$install_dir"
}

build_anvio() {
  local install_dir="$1"
  if [[ "$SKIP_BUILD" -eq 1 ]]; then
    warn "Skipping build (--skip-build)"
    return
  fi
  log "Installing dependencies..."
  (cd "$install_dir" && pnpm install --frozen-lockfile 2>/dev/null || pnpm install)
  log "Building Anvio..."
  (cd "$install_dir" && pnpm build)
}

setup_workspace() {
  local install_dir="$1"

  if [[ -f "$ANVIO_WORKSPACE_DIR/anvio.yaml" ]]; then
    log "Workspace already exists: $ANVIO_WORKSPACE_DIR"
    return
  fi

  log "Creating workspace at $ANVIO_WORKSPACE_DIR ..."
  mkdir -p "$ANVIO_WORKSPACE_DIR"

  if [[ -d "$install_dir/workspace/agents" ]]; then
    log "Copying default workspace templates..."
    cp -R "$install_dir/workspace/." "$ANVIO_WORKSPACE_DIR/"
  else
    (cd "$install_dir" && node apps/cli/dist/main.js init "$ANVIO_WORKSPACE_DIR")
  fi
}

install_cli_wrapper() {
  local install_dir="$1"
  local cli_js="$install_dir/apps/cli/dist/main.js"

  if [[ ! -f "$cli_js" ]]; then
    err "CLI not built: $cli_js"
    err "Run build without --skip-build"
    exit 1
  fi

  mkdir -p "$ANVIO_BIN_DIR"

  local wrapper="$ANVIO_BIN_DIR/anvio"
  cat >"$wrapper" <<EOF
#!/usr/bin/env bash
# Anvio CLI — generated by scripts/install.sh
export ANVIO_HOME="$ANVIO_HOME"
export ANVIO_WORKSPACE="\${ANVIO_WORKSPACE:-$ANVIO_WORKSPACE_DIR}"
exec node "$cli_js" "\$@"
EOF
  chmod +x "$wrapper"
  log "Installed CLI: $wrapper"
}

ensure_path() {
  if echo ":$PATH:" | grep -q ":$ANVIO_BIN_DIR:"; then
    return
  fi

  local shell_rc=""
  if [[ -n "${ZSH_VERSION:-}" ]] || [[ "$SHELL" == *zsh* ]]; then
    shell_rc="$HOME/.zshrc"
  elif [[ -n "${BASH_VERSION:-}" ]] || [[ "$SHELL" == *bash* ]]; then
    shell_rc="$HOME/.bashrc"
  fi

  if [[ -n "$shell_rc" ]] && [[ -w "$shell_rc" ]]; then
    if ! grep -q 'ANVIO_BIN_DIR' "$shell_rc" 2>/dev/null; then
      {
        echo ''
        echo '# Anvio CLI'
        echo "export PATH=\"$ANVIO_BIN_DIR:\$PATH\""
      } >>"$shell_rc"
      warn "Added $ANVIO_BIN_DIR to PATH in $shell_rc — restart shell or: source $shell_rc"
    fi
  else
    warn "Add to PATH manually: export PATH=\"$ANVIO_BIN_DIR:\$PATH\""
  fi
}

write_env_hint() {
  local env_file="$ANVIO_HOME/env"
  cat >"$env_file" <<EOF
# Source this file: source $env_file
export ANVIO_HOME="$ANVIO_HOME"
export ANVIO_WORKSPACE="$ANVIO_WORKSPACE_DIR"
export PATH="$ANVIO_BIN_DIR:\$PATH"
# export ANTHROPIC_API_KEY=sk-ant-...
EOF
  log "Environment hints: $env_file"
}

print_done() {
  cat <<EOF

$(log "Installation complete")

  Workspace:  $ANVIO_WORKSPACE_DIR
  CLI:        $ANVIO_BIN_DIR/anvio

Quick start:
  export PATH="$ANVIO_BIN_DIR:\$PATH"
  export ANTHROPIC_API_KEY=your-key   # optional — mock mode without it
  anvio chat --agent architect
  anvio agents list
  anvio init ~/my-workspace

Docs: $ANVIO_HOME/app/README.md (after clone) or https://github.com/viantonugroho11/Anvio

EOF
}

main() {
  log "Anvio installer (local-first, no Docker required)"
  check_node
  ensure_pnpm

  local install_dir
  install_dir="$(detect_install_dir)"

  # Keep metadata under ~/.anvio even when installing from a dev clone
  if [[ "$install_dir" != "$ANVIO_HOME/app" ]]; then
    mkdir -p "$ANVIO_HOME"
    if [[ ! -e "$ANVIO_HOME/app" ]]; then
      ln -sfn "$install_dir" "$ANVIO_HOME/app"
    fi
  fi

  install_source "$install_dir"
  build_anvio "$install_dir"
  setup_workspace "$install_dir"
  install_cli_wrapper "$install_dir"
  ensure_path
  write_env_hint
  print_done
}

main "$@"
